version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ipickle-backend
    command: "uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app